-- Auto-generated from schema-map-postgres.yaml (map@74ce4f4)
-- engine: postgres
-- table:  sync_batch_items

CREATE TABLE IF NOT EXISTS sync_batch_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL,
  event_key CHAR(36) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  error TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_sync_batch_event UNIQUE (batch_id, event_key),
  CONSTRAINT chk_sbi_status CHECK (status IN ('pending','sent','applied','failed','skipped'))
);
